package frc.robot;

public enum lineFolowerSensorStates {
RIGHTSENSOROFFLINE, RIGHTSENSORHALFONLINE, RIGHTSENSORONLINE, MIDSENSOROFFLINE, MIDSENSORHALFONLINE, 
MIDSENSORONLINE, LEFTSENSOROFFLINE, LEFTSENSORHALFONLINE, LEFTSENSORONLINE;
}